name: Run checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  checks:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle
      - uses: gradle/gradle-build-action@v2.4.2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
          
      - name: Run unit tests
        run: ./gradlew check