name: Run checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  checks:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v5

      - name: Run unit tests
        run: ./gradlew check