name: Publish release

on:
  push:
    tags:
      - 'v*' # push events to matching v*, i.e. v1.0, v2.1.5
  workflow_dispatch:

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  deploy-release:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.repository == 'rmyhal/contentment'
    needs: [ checks ]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v5

      - name: Publish release
        run: ./gradlew clean publishAndReleaseToMavenCentral --no-daemon --no-parallel --no-configuration-cache --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_SIGNING_PASSWORD }}
